from django.urls import path
from . import views

urlpatterns = [
    path(
        "api/access/status/",
        views.AccessSystemStatus.as_view(),
        name="AccessSystemStatus",
    ),
    path(
        "api/access/permissions/",
        views.UserAccessPermissions.as_view(),
        name="UserAccessPermissions",
    ),
    path(
        "api/access/doors/<int:door_id>/authorise/<int:user_id>/",
        views.AuthoriseDevice.as_view(),
        name="AuthoriseDoor",
    ),
    path(
        "api/access/doors/<int:door_id>/revoke/<int:user_id>/",
        views.RevokeDevice.as_view(),
        name="RevokeDoor",
    ),
    path(
        "api/access/interlocks/<int:interlock_id>/authorise/<int:user_id>/",
        views.AuthoriseDevice.as_view(),
        name="AuthoriseInterlock",
    ),
    path(
        "api/access/interlocks/<int:interlock_id>/revoke/<int:user_id>/",
        views.RevokeDevice.as_view(),
        name="RevokeInterlock",
    ),
    path(
        "api/access/interlocks/<int:interlock_id>/reboot/",
        views.RebootDevice.as_view(),
        name="RebootInterlock",
    ),
    path(
        "api/access/doors/<int:door_id>/reboot/",
        views.RebootDevice.as_view(),
        name="RebootDoor",
    ),
    path(
        "api/access/doors/<int:door_id>/sync/",
        views.SyncDevice.as_view(),
        name="SyncDoor",
    ),
    path(
        "api/access/interlocks/<int:interlock_id>/sync/",
        views.SyncDevice.as_view(),
        name="SyncInterlock",
    ),
    path(
        "api/access/memberbucks-devices/<int:memberbucks_device_id>/sync/",
        views.SyncDevice.as_view(),
        name="SyncMemberbucksDevice",
    ),
    path(
        "api/access/doors/<int:door_id>/bump/",
        views.BumpDoor.as_view(),
        name="BumpDoor",
    ),
    path(
        "api/access/doors/<int:door_id>/lock/",
        views.LockDevice.as_view(),
        name="LockDoor",
    ),
    path(
        "api/access/doors/<int:door_id>/unlock/",
        views.UnlockDevice.as_view(),
        name="UnlockDoor",
    ),
    path(
        "api/access/interlocks/<int:interlock_id>/lock/",
        views.LockDevice.as_view(),
        name="LockInterlock",
    ),
    path(
        "api/access/interlocks/<int:interlock_id>/unlock/",
        views.UnlockDevice.as_view(),
        name="UnlockInterlock",
    ),
]
