# Generated by Django 5.2.17 on 2026-09-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberbucks", "0008_alter_memberbucks_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberbucks",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("stripe", "Stripe Top-up"),
                    ("bank", "Bank Transfer"),
                    ("cash", "Cash"),
                    ("card", "Membership Card"),
                    ("interlock", "Interlock Cost"),
                    ("web", "Portal Payment"),
                    ("other", "Other"),
                ],
                max_length=10,
                verbose_name="Transaction Type",
            ),
        ),
    ]
