# Generated by Django 5.2.17 on 2026-08-31 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0017_alter_log_logtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_memberbucks_purchase',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
